version: 2

build:
  os: ubuntu20
  languages:
    python: "3.9"
  apt_packages:
    - libkrb5-dev

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
   configuration: docs/conf.py
