site_name: wunderkafka
repo_url: https://github.com/severstal-digital/wunderkafk://github.com/severstal-digital/wunderkafka
repo_name: severstal-digital/wunderkafka

theme:
  name: "material"
  features:
   - content.code.copy

nav:
  - Home: index.md
  - Installation: pages/install.md
  - QuickStart: pages/quickstart.md
  - Advanced: pages/advanced_usage.md
  - API: pages/API.md
  - Advanced API: pages/advanced_API.md

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - markdown_include.include:
        base_path: docs
