[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version="py39"
exclude = [
	"wunderkafka/config/generated/*",
	"examples/*"
]
