name: Doc test

on:
  push:
    branches:
      - docs-update

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install doc dependencies
        run: pip install -r dev_docs/requirements.txt
      - uses: actions/cache@v4
        with:
          key: mkdocs-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-
      - run: mkdocs gh-deploy -d .
