name: pull-request

on:
  pull_request:
    branches:
      - master

env:
  TODO_COUNT_BADGE_PATH: .github/assets/todo-count-badge.svg

jobs:
  independent:
    if: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pydantic-settings-version: [ '~=2.0.0', '']
        # ToDo (tribunsky.kir): make avro extra too but do not forget to require requests in the sake of SRs
        dataclasses-avroschema-version: [ '==0.53.0', '~=0.53.0', '==0.54.0', '~=0.60.0', '']
        python-version: ['3.9', '3.10', '3.11', '3.12']
    container: python:${{ matrix.python-version }}-slim-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up uv venv
        run: |
          uv venv
          uv pip install attrs cachetools httpx requests
      - name: install system dependencies
        run: |
          apt-get update
          apt-get install -y librdkafka1
      - name: install confluent-kafka w/o SASL/SSL support
        run: |
          uv pip install confluent-kafka[avro]~=2.5.3
      - name: Install testing dependencies
        run: |
          if uv pip install pytest pydantic-settings${{ matrix.pydantic-settings-version }} dataclasses-avroschema${{ matrix.dataclasses-avroschema-version }}; then
              echo "Installed dependencies simultaneously"
          else
              echo "Error resolving dependencies... Installing consequently"
              uv pip install pytest 
              uv pip install pydantic-settings${{ matrix.pydantic-settings-version }} 
              uv pip install dataclasses-avroschema${{ matrix.dataclasses-avroschema-version }}
          fi
      - name: run pytest
        run: uv run pytest -s tests/
      - name: Install dependencies
        run: |
          uv pip install -U mypy==1.10.0
      - name: run mypy
        run: uv run mypy --config pyproject.toml .
  checks:
    if: false
    needs: [independent]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pydantic-settings-version: ['~=2.0.0', '']
        dataclasses-avroschema-version: [ '==0.53.0', '~=0.53.0', '==0.54.0', '~=0.60.0','']
        python-version: ['3.9', '3.10', '3.11', '3.12']
        requests-kerberos-version: ['==0.13.0']
        confluent-kafka-version: ['~=2.5.3', '']
    container: python:${{ matrix.python-version }}-slim-bookworm
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up uv venv
      run: |
        uv venv
        uv pip install attrs cachetools httpx requests    
    - name: Install system dependencies
      run: |
        apt-get update && \
        apt-get install -y librdkafka1 \
                           krb5-user \
                           libsasl2-modules-gssapi-mit \
                           librdkafka-dev \
                           libsasl2-dev \
                           libkrb5-dev \
                           libssl-dev \
                           g++
    - name: Install testing dependencies
      run: |
        if uv pip install pytest pydantic-settings${{ matrix.pydantic-settings-version }} dataclasses-avroschema${{ matrix.dataclasses-avroschema-version }} requests-kerberos${{ matrix.requests-kerberos-version }} confluent-kafka[avro]${{ matrix.confluent-kafka-version }}; then
            echo "Installed dependencies simultaneously"
        else
            echo "Error resolving dependencies... Installing consequently"
            uv pip install pytest
            uv pip install pydantic-settings${{ matrix.pydantic-settings-version }}
            uv pip install dataclasses-avroschema${{ matrix.dataclasses-avroschema-version }}
            uv pip install requests-kerberos${{ matrix.requests-kerberos-version }}
            uv pip install confluent-kafka[avro]${{ matrix.confluent-kafka-version }}
        fi
    - name: run pytest
      run: uv run pytest -s tests/
    - name: Install dependencies
      run: |
        uv pip install -U mypy==1.10.0
    - name: run mypy
      run: uv run mypy --config pyproject.toml .

  version:
    if: false
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Switch branch
        run: git checkout $GITHUB_HEAD_REF

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.19.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  todo_counter:
    runs-on: ubuntu-latest
    name: Generate todo-counter Badge
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Count Todo
        id: count_todo
        run: grep -riw "todo" wunderkafka tests | wc -l | xargs
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        with:
          label: 'TODOs'
          status: ${{ steps.count_todo.outputs.stdout }}
          path: ${{ env.TODO_COUNT_BADGE_PATH }}
          color: ${{
            steps.count_todo.outputs.stdout < 5  && 'green'              ||
            steps.count_todo.outputs.stdout < 10 && 'yellow,green'       ||
            steps.count_todo.outputs.stdout < 15 && 'yellow'             ||
            steps.count_todo.outputs.stdout < 20 && 'orange,yellow'      ||
            steps.count_todo.outputs.stdout < 25 && 'orange'             ||
            steps.count_todo.outputs.stdout < 30 && 'red,orange'         ||
            steps.count_todo.outputs.stdout < 35 && 'red,red,orange'     ||
            steps.count_todo.outputs.stdout < 40 && 'red,red,red,orange' ||
            'red' }}
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v16
        id: verify-changed-files
        with:
          files: ${{ env.TODO_COUNT_BADGE_PATH }}
      - name: Commit badge
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $TODO_COUNT_BADGE_PATH
          git commit -m "chore: update todo-counter badge"

      - name: Push badge commit
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          branch: ${{ github.head_ref }}
  deploy:
    if: false
    needs: [checks, version]
    runs-on: ubuntu-latest
    environment: test-release
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install packaging dependencies
      run: pip install build
    - uses: actions/checkout@v4
    - name: sed version
      run: |
        echo "Got version from vcs: ${{ needs.version.outputs.tag }}"
        sed -i 's/version = \"0.0.0\"/version = \"${{ needs.version.outputs.tag }}\"/' pyproject.toml
        cat pyproject.toml | grep -i version
    - name: Build package
      run: python -m build
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
