name: release

on:
  workflow_dispatch: null
  release:
    types:
      - published

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Switch branch
        run: git checkout ${{ github.ref_name }}

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.19.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [version]
    runs-on: ubuntu-latest
    environment: release
    permissions:
       id-token: write
    steps:
    - name: Install packaging dependencies
      run: pip install build
    - uses: actions/checkout@v4
    - name: sed version
      run: |
        echo "Got version from vcs: ${{ needs.version.outputs.tag }}"
        sed -i 's/version = \"0.0.0\"/version = \"${{ needs.version.outputs.tag }}\"/' pyproject.toml
        cat pyproject.toml | grep -i version
    - name: Build package
      run: python -m build
    - name: Publish package to real PyPI
      uses: pypa/gh-action-pypi-publish@release/v1


  docs:
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install doc dependencies
        run: pip install -r dev_docs/requirements.txt
      - uses: actions/cache@v4
        with:
          key: mkdocs-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-
      - run: |
          mkdocs gh-deploy --force
